import { execFileSync } from 'node:child_process'
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { afterAll, describe, expect, it } from 'vitest'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const PS = join(ROOT, 'tools', 'install.ps1')
const JS = join(ROOT, 'tools', 'install.mjs')
const BOM = '﻿'

const LAUNCHER =
  '{"name":"BY/GT_CheatLauncher","status":true,"description":"F9 cheat window",' +
  '"parameters":{"CheatEnabled":"true","CheatPath":"./.cheat","DebugKey":"debug"}}'
const OTHER = '{"name":"BY_MessageWindow","status":true,"description":"日本語","parameters":{"x":"1"}}'

const PLUGINS_JS = [
  '//=============================================================================',
  '// Generated by RPG Maker.',
  '//=============================================================================',
  '',
  'var $plugins =',
  '[',
  `${LAUNCHER},`,
  OTHER,
  '];',
  ''
].join('\n')

const hasPowerShell = (() => {
  try {
    execFileSync('powershell', ['-NoProfile', '-Command', 'exit 0'], { stdio: 'ignore' })
    return true
  } catch {
    return false
  }
})()

const scratch = mkdtempSync(join(tmpdir(), 'cheatui-'))

afterAll(() => rmSync(scratch, { recursive: true, force: true }))

interface Game {
  root: string
  content: string
  pluginsJs: string
}

function makeGame({ engine = 'MZ', bom = false } = {}): Game {
  const root = mkdtempSync(join(scratch, 'game-'))
  const content = engine === 'MV' ? join(root, 'www') : root
  const js = join(content, 'js')

  mkdirSync(js, { recursive: true })
  writeFileSync(join(content, 'index.html'), '<html></html>')
  writeFileSync(join(js, engine === 'MV' ? 'rpg_core.js' : 'rmmz_core.js'), '// engine')
  writeFileSync(join(js, 'main.js'), '// main')
  writeFileSync(join(js, 'plugins.js'), (bom ? BOM : '') + PLUGINS_JS, 'utf-8')
  writeFileSync(join(root, 'Game.exe'), 'MZ')

  return { root, content, pluginsJs: join(js, 'plugins.js') }
}

const runPs = (args: string[]) =>
  execFileSync('powershell', ['-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', PS, '-NoPrompt', ...args], {
    encoding: 'utf-8'
  })

const runNode = (args: string[]) => execFileSync(process.execPath, [JS, ...args], { encoding: 'utf-8' })

function readPlugins(game: Game): string {
  const text = readFileSync(game.pluginsJs, 'utf-8')
  return text.startsWith(BOM) ? text.slice(1) : text
}

function entries(game: Game): { name: string; status: boolean; parameters: Record<string, string> }[] {
  const text = readPlugins(game)
  return JSON.parse(text.slice(text.indexOf('['), text.lastIndexOf(']') + 1))
}

describe('installer', () => {
  it('registers the plugin without rewriting existing entries', () => {
    const game = makeGame()
    runNode([game.root])

    const list = entries(game)

    expect(list).toHaveLength(3)
    expect(list[2].name).toBe('CheatUILoader')
    expect(list[2].parameters).toEqual({ assetDir: 'cheat-ui', defaultLocale: 'auto' })
    expect(readPlugins(game)).toContain(OTHER)
    expect(readPlugins(game).startsWith('//=====')).toBe(true)
  })

  it('copies the build output and never touches main.js', () => {
    const game = makeGame()
    const before = readFileSync(join(game.content, 'js', 'main.js'), 'utf-8')

    runNode([game.root])

    expect(existsSync(join(game.content, 'cheat-ui', 'cheat-ui.js'))).toBe(true)
    expect(existsSync(join(game.content, 'cheat-ui', 'cheat-ui.css'))).toBe(true)
    expect(existsSync(join(game.content, 'js', 'plugins', 'CheatUILoader.js'))).toBe(true)
    expect(readFileSync(join(game.content, 'js', 'main.js'), 'utf-8')).toBe(before)
  })

  it('switches off a cheat launcher whose folder does not exist', () => {
    const game = makeGame()
    runNode([game.root])

    const launcher = entries(game).find((entry) => entry.name === 'BY/GT_CheatLauncher')!

    expect(launcher.status).toBe(false)
    expect(launcher.parameters.CheatPath).toBe('./.cheat')
  })

  it('leaves a cheat launcher alone when its folder is really there', () => {
    const game = makeGame()
    mkdirSync(join(game.content, '.cheat'), { recursive: true })

    runNode([game.root])

    expect(entries(game).find((entry) => entry.name === 'BY/GT_CheatLauncher')!.status).toBe(true)
  })

  it('is idempotent', () => {
    const game = makeGame()
    runNode([game.root])
    const first = readPlugins(game)
    runNode([game.root])

    expect(entries(game).filter((entry) => entry.name === 'CheatUILoader')).toHaveLength(1)
    expect(readPlugins(game)).toBe(first)
  })

  it('refreshes its own entry when upgrading from an older install', () => {
    const game = makeGame()
    const stale = readPlugins(game).replace(
      '];',
      '{"name":"CheatUILoader","status":true,"description":"old","parameters":{"cheatDir":"cheat"}}\n];'
    )

    writeFileSync(game.pluginsJs, stale.replace(OTHER, `${OTHER},`), 'utf-8')
    runNode([game.root])

    const ours = entries(game).filter((entry) => entry.name === 'CheatUILoader')

    expect(ours).toHaveLength(1)
    expect(ours[0].parameters).toEqual({ assetDir: 'cheat-ui', defaultLocale: 'auto' })
  })

  it('writes nothing on a dry run', () => {
    const game = makeGame()
    const before = readPlugins(game)

    runNode([game.root, '--dry-run'])

    expect(readPlugins(game)).toBe(before)
    expect(existsSync(join(game.content, 'cheat-ui'))).toBe(false)
  })

  it('never destroys a folder the game already owns', () => {
    const game = makeGame()
    const theirs = join(game.content, 'cheat-ui')

    mkdirSync(theirs, { recursive: true })
    writeFileSync(join(theirs, 'their-file.js'), '// the game owns this', 'utf-8')

    runNode([game.root])

    const kept = readdirSync(game.content).find((entry) => entry.startsWith('cheat-ui.cheatui-backup-'))

    expect(kept, 'the original folder is moved aside, not deleted').toBeDefined()
    expect(existsSync(join(game.content, kept!, 'their-file.js'))).toBe(true)
    expect(existsSync(join(theirs, 'cheat-ui.js'))).toBe(true)
  })

  it('detects the MV layout under www/', () => {
    const game = makeGame({ engine: 'MV' })

    expect(runNode([game.root])).toMatch(/engine\s+MV/)
    expect(existsSync(join(game.root, 'www', 'cheat-ui', 'cheat-ui.js'))).toBe(true)
  })
})

describe.runIf(hasPowerShell)('powershell installer', () => {
  it('accepts a plugin parameter with an empty name, as MOG plugins ship', () => {
    // PowerShell 5.1 の ConvertFrom-Json はこれを拒む。実在のゲームで詰まった。
    const game = makeGame()
    const withEmptyKey = readPlugins(game).replace(
      OTHER,
      '{"name":"MOG_TitlePictureCom","status":true,"description":"","parameters":{"":"1","x":"2"}}'
    )

    writeFileSync(game.pluginsJs, withEmptyKey, 'utf-8')
    runPs(['-GamePath', game.root])

    expect(entries(game).map((entry) => entry.name)).toContain('CheatUILoader')
    expect(readPlugins(game)).toContain('"parameters":{"":"1","x":"2"}')
  })

  it('accepts any path inside the game', () => {
    const game = makeGame()
    runPs(['-GamePath', join(game.root, 'Game.exe')])

    expect(entries(game)).toHaveLength(3)
    expect(existsSync(join(game.content, 'cheat-ui', 'cheat-ui.js'))).toBe(true)
  })

  it('preserves the BOM it found', () => {
    const withBom = makeGame({ bom: true })
    const without = makeGame()

    runPs(['-GamePath', withBom.root])
    runPs(['-GamePath', without.root])

    expect(readFileSync(withBom.pluginsJs, 'utf-8').startsWith(BOM)).toBe(true)
    expect(readFileSync(without.pluginsJs, 'utf-8').startsWith(BOM)).toBe(false)
  })

  it('refuses a folder that is not a game', () => {
    const empty = mkdtempSync(join(scratch, 'empty-'))

    expect(() => runPs(['-GamePath', empty])).toThrow()
  })

  it('removes exactly what it installed', () => {
    const game = makeGame()
    runPs(['-GamePath', game.root])
    runPs(['-GamePath', game.root, '-Uninstall'])

    expect(entries(game)).toHaveLength(2)
    expect(existsSync(join(game.content, 'cheat-ui'))).toBe(false)
    expect(existsSync(join(game.content, 'js', 'plugins', 'CheatUILoader.js'))).toBe(false)
    expect(readPlugins(game)).toContain(OTHER)
  })

  it('agrees with the node installer byte for byte', () => {
    const viaPs = makeGame()
    const viaNode = makeGame()

    runPs(['-GamePath', viaPs.root])
    runNode([viaNode.root])

    expect(readPlugins(viaPs)).toBe(readPlugins(viaNode))
  })
})
